Repository philippreiner/planb-nextjs, pull requests merged in 2021-09, with the labels that each got.

#37 Major bugfixes
  components/header/header.js
  pages/karriere.js
  public/images/offices/huettlingen-baustelle-blured.png
Labels: bug, enhancement, content, newfeature

#60 Ready for Launch - Small fixes and changes
  components/atoms/atoms.js
  components/footer/footer.js
  components/homepage/about.js
  components/homepage/solutions.js
  package-lock.json
  pages/about.js
  pages/dpf.js
  pages/imprint.js
  pages/karriere.js
Labels: release:fix

#61 BugFixes - beside images & layout - additional features
  components/about/about.js
  components/hero/hero.js
  components/slider/slider.js
  pages/about.js
  pages/dpf.js
  pages/karriere.js
  pages/modern-work.js
  public/assets/icons/downarrow.png
  public/assets/icons/uparrow.png
  public/images/slider/dpf/flinki.png
  public/images/slider/dpf/luft.png
Labels: bug, enhancement, content, design, release:fix

#68 fixed images
  components/headlinecollection/headlinecollection.js
  components/homepage/about.js
  components/homepage/career.js
  components/homepage/culture.js
  components/homepage/solutions.js
  components/slider/slider.js
  pages/about.js
  pages/dpf.js
  pages/index.js
  pages/karriere.js
  pages/mitarbeiter.js
  pages/modern-work.js
  public/images/microsoft/gold_a.png
  public/images/microsoft/gold_d.png
  public/images/microsoft/silver.png
  public/images/slider/dpf/MRCS-Mockup-3.png
  public/images/slider/dpf/_oldMRCS-Mockup-3.png
  public/images/slider/dpf/flinki.png
  public/images/slider/dpf/hauptversammlung.png
  public/images/slider/dpf/luft.png
  public/images/slider/dpf/old_flinki.png
  public/images/slider/dpf/old_hauptversammlung.png
  public/images/slider/dpf/old_luft.png
  public/images/slider/modern-work/old_transform-work.png
  public/images/slider/modern-work/transform_work.png
Labels: bug, content, design, release:fix

#69 fixed tablet mode AMK!
  components/slider/slider.js
Labels: bug
